name: Notify Discord

on:
  push:
    branches:
      - '**'

jobs:
  notify:
    name: Notify Discord
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.YOUR_DISCORD_WEBHOOK_SECRET }}
          content: |
            ==================
            --- NEW COMMIT ---
            ==================
            [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }}) 
            

            ======================
            --- COMMIT MESSAGE ---
            ======================
            ${{ github.event.head_commit.message }}
            
